### ISSUE TITLE
Incorrect scenario amount in summary

### ISSUE THREAD

**Issue by andrcuns** [rmpestano/cukedoctor#101]
In case feature contains Background steps, summary section's scenario amount is multiplied by 2.

Here is the json to reproduce issue:
[features.json.zip](https://github.com/rmpestano/cukedoctor/files/1704203/features.json.zip)

**Comment by rmpestano** [comment]
Linking commits related to this issue (the `refs` on the commits were wrong):

* 7fc502c7d634532a97ca74111b540bfb11e2d573
* 7aeaeacbd051097e5a7134d6f0b20bec663a44b7

**Comment by rmpestano** [comment]
Hi @andrcuns,

can you try with v1.1.1-SNAPSHOT?

If you use maven you need to declare snapshots repository:

```
<repositories>
    <repository>
        <snapshots/>
        <id>snapshots</id>
        <name>libs-snapshot</name>
        <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
</repositories>
``` 

The "cli" version [can be found here](https://oss.sonatype.org/content/repositories/snapshots/com/github/cukedoctor/cukedoctor-main/1.1.1-SNAPSHOT/cukedoctor-main-1.1.1-20180209.192919-2.jar):  


I've tested your feature and got 4 scenarios (backgrounds are not being considered as scenarios) and 18 steps (backgroud steps are included here).

**Comment by andrcuns** [comment]
Hi @rmpestano 
Yep, with SNAPSHOT all good now. Since we use cukedoctor to embed live doc in our wiki, this fix would help a lot to have correct information about executed scenario amount.

**Comment by rmpestano** [comment]
Great, will release v1.1.1  soon wth this fix, thanks for reporting.

**Comment by rmpestano** [comment]
V1.1.1 should be on maven central now.
