### ISSUE TITLE
Add to Cucumber documentation

### ISSUE THREAD

**Issue by mlvandijk** [rmpestano/cukedoctor#116]
Hi, this looks like a handy tool with nice documentation. Would you be willing to 1. add it as a related tool to the Cucumber documentation (here: https://docs.cucumber.io/tools/related-tools/) or even help out more with the Cucumber documentation itself (here: https://github.com/cucumber/docs.cucumber.io)

**Comment by rmpestano** [comment]
Just created the [PR](https://github.com/cucumber/docs.cucumber.io/pull/285).

**Comment by rmpestano** [comment]
Thanks for the interest on having this tool on the Cucumber docs site ;)

**Comment by mlvandijk** [comment]
Thank you! Please let us know if you're willing to help out with Cucumber documentation. Would love the help ;)
