### ISSUE TITLE
Cucumber-jvm 2.x support

### ISSUE THREAD

**Issue by rmpestano** [rmpestano/cukedoctor#117]
Cucumber 2.x has upgraded Gherkin and **do not support feature and step comments** anymore.

For Cukedoctor this has impact on **3** main features:

**1 -** The first one is obvious, we lost step and feature comments. The feature comment has not much advantage because we can use Asciidoc in feature/scenario description. 

For the step comment there is not much we can do, in fact steps must be self explanatory.

**2 -** Now the second feature we lost is [Asciidoc markup on docstrings ](https://github.com/rmpestano/cukedoctor#672-asciidoc-markup-in-docstrings) . This will not work in cucumber-jvm 2.x **because the feature is enabled in cukedoctor by a step comment**.

To make Asciidoc markup work in cucumber 2.x we need to activate the feature using another mechanism. My first idea is to use a tag named `@Asciidoc` e.g:

```
@asciidoc
Feature: Discrete class feature

  Scenario: Render source code

    Given the following source code
    """
[source, java]
-----
public int sum(int x, int y){
        int result = x + y;
        return result; (1)
    }
-----
<1> We can have callouts in living documentation
    """

  Scenario: Render table

    Given the following table
    """
|====

| Cell in column 1, row 1 | Cell in column 2, row 1
| Cell in column 1, row 2 | Cell in column 2, row 2
| Cell in column 1, row 3 | Cell in column 2, row 3

|====
    """
```

Note that tags can be only used at [feature and scenario/scenario-outline](https://docs.cucumber.io/cucumber/api/#tags) level.

**3 -** The third feature that is affected is [feature ordering](https://github.com/rmpestano/cukedoctor#66-feature-ordering)  because it also uses comments for ordering. 

 I'm also inclined to use tags for ordering:

```
@order-1
Feature: Calculator

  Scenario: Adding numbers
```

Also note that the special tags `@Asciidoc` and the tag for order will not be rendered on resulting living documentation

**Comment by rmpestano** [comment]
fixed by #133 and available in `cukedoctor 2.0`

**Comment by andrewesweet** [comment]
To properly demonstrate compatibility with cucumber-jvm-5, would it be worthwhile reproducing all of the existing cucumber report json fixtures using 5.6.0 and adding test cases for them, or replacing them if cuke 1.x backwards compatibility is not desired?

**Comment by rmpestano** [comment]
Hi @andrewesweet, I have migrated cukedoctor documentation to use Cucumber 5.6, see #137. 

Note that Cukedoctor 2.0 should be backward compatible so If you use Cucumber 1.x you'll be able to upgrade to cukedoctor 2
