### ISSUE TITLE
PDF format cannot be generated on windows platform

### ISSUE THREAD

**Issue by thomas-breining** [rmpestano/cukedoctor#119]
When trying to generate the pdf format from a windows machine, asciidoctor fails with the following.
```
org.jruby.exceptions.RaiseException: (SystemCallError) Unknown error (SystemCallError) 123 - FindFirstFile
```

This behavior can be reproduced by running the existing tests on a windows host.

Here are the details of the machine I reproduced it on.
```
C:\>mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.0\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

[Here is the related maven output](https://github.com/rmpestano/cukedoctor/files/2847862/mvn.log)

**Note:** There were some minor fixes required in the converter tests to reach the plugin module,
there are non portable line endings and path separators expected in the converter tests.

**Comment by andrewesweet** [comment]
I cannot reproduce this on Windows 10 on master; both the test suite and PDF generation work a-OK.
I've also tested Cukedoctor 2.0 maven plugin on Windows 7 and PDF generation works there too.

**Comment by rmpestano** [comment]
That's great knews! Se have updated some libs like asciidoctorj-pdf and jruby in latest release, maybe that fixed this issue
