### ISSUE TITLE
Feature Request: Generate doc from Feature Files

### ISSUE THREAD

**Issue by ralphavalon** [rmpestano/cukedoctor#121]
To generate doc today, it's needed the `cucumber.json`, which is okay. But some tools, like: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor don't generate this file and won't generate it because of Cypress limitations.

In addition, tools that normally generate doc from feature files (mostly mentioned here: https://docs.cucumber.io/tools/related-tools/) are pretty ugly. Cukedoctor's documentation is pretty, customizable and easy to use. I don't know if it's possible (or easy) to generate doc from `.feature` files but I guess it would be great. And if I can help with anything, I will.

**Comment by rmpestano** [comment]
Hi @ralphavalon,

thank you for the interest on this project and glad you like it!

About you're request , unfortunately, I don't think we should implement it in Cukedoctor. Let me explain:

Cukedoctor model classes are highly dependent on the json representation of feature files, [see here](https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-converter/src/main/java/com/github/cukedoctor/api/model). 

All these model classes are created using a json parser ([Jackson](https://github.com/FasterXML/jackson)), [see here](https://github.com/rmpestano/cukedoctor/blob/master/cukedoctor-converter/src/main/java/com/github/cukedoctor/parser/FeatureParser.java#L27   
).

So in my opinion it is easier generate the json representation from a feature file than introduce another parser on Cukedoctor which would parse feature files (on their text representation) into Cukedoctor model classes but I definitely would accept a pull request that implement such parser (e.g FeatureFileParser).

**Comment by ralphavalon** [comment]
No problem. Thanks for response. I'll see what I can do. I think we can close the issue. If I get some success, I'll send a PR hahaha thanks anyway =)
