### ISSUE TITLE
Missing Dockerfile

### ISSUE THREAD

**Issue by cvoltz** [rmpestano/cukedoctor#126]
The `Dockerfile` for the [Docker container](https://hub.docker.com/r/rmpestano/cukedoctor) is not in the repository or on the Docker Hub page or in another one of your public repositories.

**Comment by rmpestano** [comment]
Hi, there is two tags published: https://hub.docker.com/r/rmpestano/cukedoctor/tags

**Comment by cvoltz** [comment]
The tags are to the images not the source. I was looking for the Dockerfile so I could fix the problems I ran into.

**Comment by rmpestano** [comment]
The Dockerfile is here: https://github.com/rmpestano/cukedoctor/blob/master/cukedoctor-main/Dockerfile

**Comment by cvoltz** [comment]
Thanks
