### ISSUE TITLE
Rendering errors in html showing ifndef::backend-pdf[] characters

### ISSUE THREAD

**Issue by mypark** [rmpestano/cukedoctor#129]
For some reason all my feature names are being rendered with `minmax::FeatureNameGoesHere[]` when i call asciidoctor to convert the adoc to html.  It looks like it's rendering what's in `ifndef::backend-pdf[]` when I'm outputting to html. e.g.

```
ifndef::backend-pdf[]
minmax::FeatureNameGoesHere[]
endif::[]
```

Is there a setting I'm missing?

This doesn't seem to be an issue if I use the standalone jar.  I've tested against the adoc that the standalone jar uses and using the asciidoctor command line to convert the adoc that was generated by the standalone jar shows the error.

**Comment by rmpestano** [comment]
Yea, the thing is, you need [cukedoctor-extension](https://github.com/rmpestano/cukedoctor/tree/master/cukedoctor-extension) on your classpath, it is responsible for converting `minmax` into a min max icon to hide/show features in html documentation.

In cukedoctor-maven plugin and cukedoctor-main the extension is already being used, don't know on your caso how you are invoking cukedoctor.

I hope it explains the issue

**Comment by mypark** [comment]
I'm using gradle

```
@CucumberOptions(plugin = {"json:target/test-output/cucumber.json"}, features = "src/test/resources/hellocucumber/features", tags = "not @manual")
```

**Comment by rmpestano** [comment]
Have you tried adding cukedoctor-extension:
```
com.github.cukedoctor: cukedoctor-extension:1.2.1
```

Also I think you'll have problems with cucumber version greater than 1.x, see here:https://github.com/rmpestano/cukedoctor/issues/117

**Comment by mypark** [comment]
new to gradle, I tried putting the class path like so in buildscript dependencies and  in the asciidoctor object, what's the right place for it to go?

```
buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'org.asciidoctor:asciidoctor-gradle-plugin:1.5.9.2',
        classpath 'com.github.cukedoctor:cukedoctor-extension:1.2.1'
    }
}

```

**Comment by rmpestano** [comment]
Hi, I'm also new to gradle, I think the best approach is to use cukedoctor-main (It has the cukedoctor-extension embeded), you can download and execute the jar on your gradle build
