### ISSUE TITLE
including image in the report

### ISSUE THREAD

**Issue by lwiechec** [rmpestano/cukedoctor#142]
Hi, I tried to follow both Asciidoctor's documentation as well as some examples from here and there and I still fail - and I would like to include an image (from URL) in the Cukedoctor's report.

So, In my scenario, I put:

```gherkin
@sync
Feature: Test synchronization 
  Background:

    The topology can be found here:

    ===
    image::https://some/http/page/image.png[test, 600, 800]
    ===

    Given configuration is
    ...
```

page is rendered still with no image. What am I doing wrong?...

**Comment by andrewesweet** [comment]
I’m not certain, but have you looked at the _ allowUriRead_ configuration option? It is **false** by default.

**Comment by rmpestano** [comment]
Hi @lwiechec, you can set allowUriRead in cukedoctor maven plugin [like this](https://github.com/rmpestano/cukedoctor/blob/a288c6b63e2fbbfb22e2de657793f89767492b79/cukedoctor-converter/pom.xml#L164) or in cukedoctor main using the `-allowUriRead` flag

I hope it helps.
