### ISSUE TITLE
Setting header attributes

### ISSUE THREAD

**Issue by andrewesweet** [rmpestano/cukedoctor#143]
I want to use Asciidoc’s stem support (https://asciidoctor.org/docs/user-manual/#activating-stem-support) to include equations in my generated docs. This requires a header attribute to be set. Does cukedoctor have a hook that can be used to set these, please?

**Comment by rmpestano** [comment]
Hi @andrewesweet, we have only pre [defined attributes](https://github.com/rmpestano/cukedoctor/blob/master/cukedoctor-converter/src/main/java/com/github/cukedoctor/api/DocumentAttributes.java) that Cukedoctor maven plugin and cukedoctor-cli set when they [create cukedoctor instance(https://github.com/rmpestano/cukedoctor/blob/f28f248e833cfcd58a168d9240ee69359730b69a/cukedoctor-main/src/main/java/com/github/cukedoctor/CukedoctorMain.java#L175).

I think we can add a new attribute to support stem

**Comment by andrewesweet** [comment]
Now available on master (#144).
