### ISSUE TITLE
Improve formatting in Feature and Scenario descriptions

### ISSUE THREAD

**Issue by andrewesweet** [rmpestano/cukedoctor#154]
Cukedoctor currently passes along a Feature or Scenario description's leading whitespace to AsciiDoc, except the first line. She problem is that whitespace is often formatting the _feature file_ rather than _desired indentation of the description paragraph block in AsciiDoc_. e.g. My features are indented one tab, so their descriptions are two tabs; my scenarios are indented two tabs, so their descriptions are indented three tabs etc..

I think Cukedoctor should look at the indentation of the first non-blank line of a description and trim however many character of leading whitespace are in that line off all other lines i.e. treat leading whitespace in the first line as _formatting the feature file_ and any subsequent additional leading whitespace on other lines as _formatting the description block_.

E.g.

<pre>
    This is the description for Feature One. The first non-blank line of this description in the feature file began with four whitespace characters.
      Therefore, cukedoctor will ignore up to the first four
whitespace characters
  in all other lines in the same description,
    if any are present.

This includes
  further lines
    in a different
      paragraph
        in the same description.
</pre>

should be rendered as
<pre>
This is the description for Feature One. The first non-blank line of this description in the feature file began with four whitespace characters.
  Therefore, cukedoctor will ignore up to the first four
whitespace characters
in all other lines in the same description,
if any are present.

This includes
further lines
in a different
  paragraph
    in the same description. 
</pre>

as opposed to the current
<pre>
This is the description for Feature One. The first non-blank line of this description in the feature file began with four whitespace characters.
      Therefore, cukedoctor will ignore up to the first four
whitespace characters
  in all other lines in the same description,
    if any are present.

This includes
  further lines
    in a different
      paragraph
        in the same description.
</pre>

**Comment by rmpestano** [comment]
Hi @andrewesweet, why your feature files has such formating? isn't it easier to adjust the feature description instead of trying to fix that in Cukedoctor?

Also for your PR #155, please rebase your branch with cukedoctor master branch or create a new branch on top of master and add your changes on this branch. It will be easier to review your changes.

**Comment by andrewesweet** [comment]
Sorry - I missed the lack of rebase, although the PR makes it obvious. Will fix.

Regarding the formatting, the style shown in the Gherkin online reference and in the most commonly used IntelliJ plugin for Cucumber JVM both use indentation of Scenarios under features and align the descriptions accordingly.

**Comment by rmpestano** [comment]
I've rebased master commits into your branch otherwise we would not be able to merge your PR because the repositories trees were different. 

Let's wait CI build and then merge the PR, thank you very much!

**Comment by rmpestano** [comment]
The fix for this is available in `v3.1`. Thank you @andrewesweet!

**Comment by andrewesweet** [comment]
Thank you!
