### ISSUE TITLE
Add support for Asciidoctor Diagram

### ISSUE THREAD

**Issue by andrewesweet** [rmpestano/cukedoctor#167]
I quite commonly want to include diagrams in my documentation. So much better if those diagrams themselves can be code artefacts. [AsciidoctorJ-Diagram](https://github.com/asciidoctor/asciidoctorj-diagram) helps to achieve this. It is one of the official AsciiDoctor extensions (the Java wrapper too) so I feel comfortable with suggesting it be included in the Cukedoctor distribution.

If there is future demand for other extensions, we could consider creating a mechanism where those extensions can be registered by the consumer (as per -r extensionname in vanilla Asciidoctor). Until such demand is realised, I feel it is OK to directly include this popular, official extension.

**Comment by rmpestano** [comment]
Really nice idea and contribution @andrewesweet! 

> If there is future demand for other extensions, we could consider creating a mechanism where those extensions can be registered by the consumer...

Sure, let's do that.

Thank you one more time!
