### ISSUE TITLE
Main jar not found in Bintray

### ISSUE THREAD

**Issue by sashokbg** [rmpestano/cukedoctor#189]
Hello,

It seems the main jar is not uploaded to the bintray and the link returns 404:

https://bintray.com/artifact/download/rmpestano/cukedoctor/com/github/cukedoctor/cukedoctor-main/3.5.2/cukedoctor-main-3.5.2.jar

![image](https://user-images.githubusercontent.com/10643824/118393144-d18ef780-b63d-11eb-8fc3-200ea99f190f.png)

I also tried searching bintray manually for "cukedoctor" which returns a result but all links are 404.

Thank you for your help

EDIT: added screenshot

**Comment by rmpestano** [comment]
Hi @sashokbg, just updated the readme with the new link. Thanks for the heads up!
