### ISSUE TITLE
Be able to use i18n for recent Cucumber versions

### ISSUE THREAD

**Issue by rdlopes** [rmpestano/cukedoctor#262]
Hi Raphaël, hope you're well,
I'm using the French i18n feature of Cukedoctor but unfortunately, Cucumber for newer versions has stopped supporting comments in JSON features, leaving us with no options in Cukedoctor but to define our own custom resource bundle.

In order to favor reuse of Cukedoctor i18n resource bundles, I've added #261 PR for using the `@language-<lang>` tag in gherkin features.

**Comment by rdlopes** [comment]
So the good PR is #264 since I couldn't refrain myself in the old one to clean everything. My OCD - not sorry 😝

**Comment by rmpestano** [comment]
Fixed by #264, thanks again @rdlopes!
