### ISSUE TITLE
skip option in mojo

### ISSUE THREAD

**Issue by r-tt** [rmpestano/cukedoctor#68]
Hello,

trivial but nice to have: a skip flag for the mojo. typically if the adoc is generated from tests and you skip tests to test something manually then you wouldn't build ATM

**Comment by rmpestano** [comment]
Hi,
:+1: 

Should be present in next release, thanks.

**Comment by rmpestano** [comment]
Hi @r-tt,

can you test in [latest snapshot](https://github.com/rmpestano/cukedoctor#distribution) (1.0.4-SNAPSHOT)?  fell free the reopen this issue if you find any problems.

**Comment by r-tt** [comment]
works well, thks! (tested only for CukedoctorMojo which is the one in my project)

**Comment by rmpestano** [comment]
:+1:
