### ISSUE TITLE
Error when trying to publish on gh pages

### ISSUE THREAD

**Issue by vikramvi** [rmpestano/cukedoctor#83]
With cukedoctor I got folder structure as per screenshot.

I have pushed these to gh pages as per http://blog.teamtreehouse.com/using-github-pages-to-host-your-website

https://github.com/vikramvi/AppiumSerenityPOC/tree/gh-pages

but when I visit https://vikramvi.github.io/AppiumSerenityPOC/ , getting 404 saying index.html is missing.

please clarify how to fix this ?

![screen shot 2016-11-24 at 5 30 07 pm](https://cloud.githubusercontent.com/assets/308490/20605442/c203a598-b26b-11e6-810a-3700a2552ea9.png)

**Comment by rmpestano** [comment]
Well I can't see index.html file here: https://github.com/vikramvi/AppiumSerenityPOC/tree/gh-pages

About generated documentation you can access it here:
https://vikramvi.github.io/AppiumSerenityPOC/target/cukedoctor-output/documentation.html

About pushing to gh-pages I am using maven-scm-plugin as described here: http://gist.asciidoctor.org/?fp-46yImsm4KUYJydq2noeJrL&source-highlighter=prettify

In your case if you want to generate in root of GH-PAGES a possible configuration would be:

```
<plugin>
    <groupId>com.github.cukedoctor</groupId>
    <artifactId>cukedoctor-maven-plugin</artifactId>
    <version>1.0.6</version>
    <configuration>
        <outputFileName>documentation</outputFileName>
        <outputDir></outputDir> 
        <!--pdf and html5 -->
        <format>all</format>
        <hideSummarySection>true</hideSummarySection>
        <hideScenarioKeyword>true</hideScenarioKeyword>
        <hideStepTime>true</hideStepTime>
        <hideFeaturesSection>true</hideFeaturesSection>
        <hideTags>true</hideTags>
        <sourceHighlighter>coderay</sourceHighlighter>
        <toc>center</toc>
        <numbered>true</numbered>
        <docVersion>${project.version}</docVersion>
    </configuration>
    <executions>
        <execution>
            <goals>
                <goal>execute</goal>
            </goals>
            <phase>verify</phase>
        </execution>
    </executions>
</plugin>
```

It will generate docs in /target/cukedoctor dir as in image below:

![print1](https://cloud.githubusercontent.com/assets/1592273/20605945/0aed0158-b255-11e6-9bf5-c95b08f9077b.png)

Then you can use scm-plugin to push target/cukedoctor folder to GH-PAGES:

```
 <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-scm-publish-plugin</artifactId>
                        <version>1.1</version>
                        <configuration>
                            <checkoutDirectory>${project.build.outputDirectory}</checkoutDirectory>
                            <checkinComment>Publishing Cukedoctor-${project.parent.version} living documentation.
                            </checkinComment>
                            <content>target/cukedoctor</content>
                            <skipDeletedFiles>true</skipDeletedFiles>
                            <pubScmUrl>scm:git:https://${GH_USER}:${GH_PASS}@github.com/rmpestano/cukedoctor.git</pubScmUrl>
                            <scmBranch>gh-pages</scmBranch>
                        </configuration>
                    </plugin>
```

**Comment by vikramvi** [comment]
I've tried as per above but couldn't see index.html getting generated.  

Does index.html gets generated automatically as part of script ?

Below is the log 

[INFO] Generating living documentation for 1 feature(s)...
Nov 24, 2016 6:45:34 PM com.github.cukedoctor.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/documentation.adoc
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/colony.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/foundation.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/rubygems.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/iconic.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/readthedocs.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/rocket-panda.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/maker.css
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.extension.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/themes/github.css
[INFO] Generated documentation at: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor
Nov 24, 2016 6:45:36 PM com.github.cukedoctor.util.FileUtil saveFile
INFO: Wrote: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor/documentation.adoc
Ignoring bond-0.5.1 because its extensions are not built.  Try: gem pristine bond --version 0.5.1
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.14 because its extensions are not built.  Try: gem pristine ffi --version 1.9.14
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
Ignoring unf_ext-0.0.7.2 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.2
[INFO] Generated documentation at: /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/cukedoctor
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ serenity-appium-mobile-native-app-automation ---
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.pom (3 KB at 8.1 KB/sec)
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.pom (2 KB at 8.4 KB/sec)
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus-components/1.1.7/plexus-components-1.1.7.pom (5 KB at 39.5 KB/sec)
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus/1.0.8/plexus-1.0.8.pom (8 KB at 57.9 KB/sec)
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar
Downloading: http://jcenter.bintray.com/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus-digest/1.0/plexus-digest-1.0.jar (12 KB at 13.5 KB/sec)
Downloaded: http://jcenter.bintray.com/org/codehaus/plexus/plexus-utils/3.0.5/plexus-utils-3.0.5.jar (226 KB at 117.5 KB/sec)
[INFO] Installing /Users/vikram-anna/Documents /serenityAppiumFlipkart/target/serenity-appium-mobile-native-app-automation-1.0-SNAPSHOT.jar to /Users/vikram-anna/.m2/repository/serenity-appium-mobile-native-app-automation/serenity-appium-mobile-native-app-automation/1.0-SNAPSHOT/serenity-appium-mobile-native-app-automation-1.0-SNAPSHOT.jar
[INFO] Installing /Users/vikram-anna/Documents /serenityAppiumFlipkart/pom.xml to /Users/vikram-anna/.m2/repository/serenity-appium-mobile-native-app-automation/serenity-appium-mobile-native-app-automation/1.0-SNAPSHOT/serenity-appium-mobile-native-app-automation-1.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:06 min
[INFO] Finished at: 2016-11-24T18:45:44+01:00
[INFO] Final Memory: 98M/1043M
[INFO] ------------------------------------------------------------------------


Please clarify if I'm missing something ?

**Comment by rmpestano** [comment]
the generated file is based on outputFileName attribute, please change  <outputFileName>documentation</outputFileName> to

```
<outputFileName>index</outputFileName>
```

**Comment by vikramvi** [comment]
ok even I thought so :)

Q1 ) I'm wondering in case I've multiple features files which generate numerous respective html files. How will they be connected to index.html ?

Q2 ) Ideally all documentation should be accessible from single entry point. 
        e.g. For email app testing all the sub-feature like sign up , sign in, composing email etc should reside in individual html files but should be connected / accessible from single source like Index page of a book.

 please clarify this

**Comment by rmpestano** [comment]
Hi,
For Q1ithe plugin will gather all features it find and create a single HTML file.

For Q2 it is not supported at the moment due to asciidoctor (the lib used to generate documentation) limitation, we could implement In cukedoctor but decided to wait for native support in asciidoctor.

**Comment by vikramvi** [comment]
Thanks a ton @rmpestano I will continue discovering your amazing library and get back with issues/suggestions.

**Comment by vikramvi** [comment]
Just fyi.. for now I'm publishing html manually as don't want to put & commit git id , pwd accidently.

https://srackham.wordpress.com/2014/12/14/publishing-a-project-website-to-github-pages/

http://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder

**Comment by rmpestano** [comment]
Hi @vikramvi, you can encrypt user and password using [travis ruby gem](https://docs.travis-ci.com/user/encryption-keys/).

**Comment by rmpestano** [comment]
> Thanks a ton @rmpestano I will continue discovering your amazing library and get back with issues/suggestions

Thank you for the feedback 👍
