### ISSUE TITLE
Rendering cucumber specification fields

### ISSUE THREAD

**Issue by Navatha24** [rmpestano/cukedoctor#86]
Hi Rafael,
Based on cucumber json output files , is it possible for cuke-doctor plugin to render specification fields (input/output) based on Test results
- Input Field (Always Green)
- Output Field (Red/Green based on Test Result)

For Eg:
Given a Thomas-Bayer customer with ID **"ID"**
When I request details about the customer with above id 
Then I can get customers **"ID", "FIRSTNAME", "LASTNAME", "STREET", "CITY"** 

**Input** -ID-**Green**
**Output**-ID, FIRSTNAME,LASTNAME,STRETT,CITY - **RED/GREEN** based on Test Result

Regards
NB

**Comment by rmpestano** [comment]
Hi @Navatha24,

It is possible but not implemented yet. 

For green inputs it is quite easy (the change would go into [StepsRenderer](https://github.com/vamsitallapudi/create-android-app-for-website.git) but for red output based on test result I don't think it would be easy and needs to be investigated. 

I just don't have time to look into it now but I accept contributions.

**Comment by Navatha24** [comment]
Thanks for the response Rafael. If I can make it work then will keep you updated.
